version: "2"

run:
  timeout: 5m

linters:
  enable:
  - asciicheck
  - unused
  - errorlint
  - gosec
  - importas
  - prealloc
  - revive
  - misspell
  - tparallel
  - unconvert
  - unparam
  - whitespace
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck

formatters:
  enable:
  - gofmt
  - goimports
