version: "2"

run:
  timeout: 5m

linters:
  enable:
  - asciicheck
  - unused
  - errorlint
  - gosec
  - importas
  - prealloc
  - revive
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - whitespace

formatters:
  enable:
  - gofmt
  - goimports

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - errcheck
