version: 2

project_name: reputer

gomod:
  proxy: false

sboms:
  - artifacts: binary

builds:
  - binary: reputer
    mod_timestamp: '{{ .CommitTimestamp }}'
    dir: cmd/reputer/
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/mchmarny/reputer/pkg/cli.version={{.Version}}
        -X github.com/mchmarny/reputer/pkg/cli.commit={{.Commit}}
        -X github.com/mchmarny/reputer/pkg/cli.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true
    name_template: 'reputer'

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    signature: "${artifact}.bundle"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all
    output: true

snapshot:
  version_template: "{{ .Tag }}-next"

report_sizes: true

release:
  github:
    owner: mchmarny
    name: reputer
  prerelease: auto
  draft: true

kos:
  - id: reputer
    build: reputer
    repositories:
      - ghcr.io/mchmarny/reputer
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{.Tag}}"
    preserve_import_paths: false
    bare: true

archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^build:"
      - "^ci:"
      - "^style:"
      - typo
      - readme

brews:
  - repository:
      owner: mchmarny
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/mchmarny/reputer"
    description: "CLI tool that calculates contributor reputation scores from Git provider APIs"
    license: "Apache-2.0"
    test: |
      system "#{bin}/reputer" "--version"
