version: 2

project_name: reputer

gomod:
  proxy: false

sboms:
  - artifacts: binary

builds:
  - binary: reputer
    mod_timestamp: '{{ .CommitTimestamp }}'
    dir: cmd/
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true
    name_template: 'reputer'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

release:
  github:
    owner: mchmarny
    name: reputer
  prerelease: auto

archives:
  - formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - readme
      - typo
      - "bump version"

brews:
  - repository:
      owner: mchmarny
      name: homebrew-reputer
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/mchmarny/reputer"
    description: "CLI tool to calculate contributor reputation from Git providers"
    directory: Formula
    license: "Apache-2.0"
    test: |
      system "#{bin}/reputer" "--version"

nfpms:
  - file_name_template: "reputer-{{.Version}}_{{.Os}}-{{.Arch}}"
    homepage: https://github.com/mchmarny/reputer/
    description: "CLI tool to calculate contributor reputation from Git providers"
    maintainer: Mark Chmarny <mchmarny@users.noreply.github.com>
    license: Apache 2.0
    vendor: mchmarny
    formats:
      - deb
      - rpm
    bindir: /usr/bin
