name: release-img
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  contents: read

jobs:

  config:
    permissions:
      contents: read
    uses: ./.github/workflows/config.yaml

  test:
    needs:
    - conf
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: ./.github/workflows/test.yaml
    with:
      go_version: ${{ needs.conf.outputs.go_version }}
      scan_severity: ${{ needs.conf.outputs.err_on_vulnerability_sev }}

  build:
    needs:
    - conf
    - test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yaml
    with:
      go_version: ${{ needs.conf.outputs.go_version }}
      image_name: ${{ needs.conf.outputs.image_name }}

  sign:
    needs:
    - conf
    - build
    permissions:
      contents: read
      actions: read
      packages: write
    uses: ./.github/workflows/sign.yaml
    with:
      cosign_version: ${{ needs.conf.outputs.cosign_version }}
      image_digest: ${{ needs.build.outputs.digest }}

  scan:
    needs:
    - conf
    - build
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/scan.yaml
    with:
      image_digest: ${{ needs.build.outputs.digest }}
      scan_severity: ${{ needs.conf.outputs.err_on_vulnerability_sev }}

  slsa:
    needs:
    - conf
    - build
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/slsa.yaml
    with:
      image_digest: ${{ needs.build.outputs.digest }}
